### ISSUE TITLE
please include Discord channel on hacash.org

### ISSUE THREAD

**Issue by kafkacell** [hacash/www1#1]
Dear team,

Technically this is not an issue, is more a request to include a Discord channel link on the website. 

I have been working on this channel and I am including guides, tutorials, videos and gathering all important information for the miners and hacashers.

Please take this into consideration and here is the HTML code link to the channel at Discord: <iframe src="https://discordapp.com/widget?id=757976908653920299&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>

Here is the regular link:  https://discord.gg/u6EA2k old one, doesnt work anymore.

Kind regards and if you need any further information do not hesitate to contact me.

**Comment by jojoin** [comment]
Ok, Thank you for your work!

**Comment by kafkacell** [comment]
Thank you very much for adding the Discod link. However the link invite became invalid. This one should be permament:

https://discord.gg/ZnuBUZM


<iframe src="https://discord.com/widget?id=757976908653920299&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>


Thanks for your support!

**Comment by jojoin** [comment]
Thank you. The link has been updated.
